import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

const SUPABASE_URL='https://yyuqodhrterfrhoyhfut.supabase.co';
const SUPABASE_KEY='sb_publishable_jSWXE3-Ckzf8UNCWgbcM7w_rsgnXXdK';
const COA_EMAIL='coa@cev.com.br';
const REFRESH_MS=2000;
const supabase=createClient(SUPABASE_URL,SUPABASE_KEY);
const $=id=>document.getElementById(id);
const pt=new Intl.NumberFormat('pt-BR',{maximumFractionDigits:0});
const pt1=new Intl.NumberFormat('pt-BR',{minimumFractionDigits:1,maximumFractionDigits:1});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const num=(v,d=0)=>{const n=Number(v);return Number.isFinite(n)?n:d};
const clone=v=>JSON.parse(JSON.stringify(v));

let currentUser=null,profile=null,busy=false,lastOk=0;
let journeys=[],mirror=null,tripFilter='ongoing',equipFilter='all',iconMap={};

function todayStart(){const d=new Date();d.setHours(0,0,0,0);return d.getTime()}
function formatTons(v){return `${pt.format(Math.max(0,num(v)))} t`}
function fmtClock(v){if(!v)return '--:--';const d=new Date(v);return Number.isNaN(d.getTime())?'--:--':d.toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}
function fmtDuration(ms){ms=Math.max(0,num(ms));const m=Math.floor(ms/60000),h=Math.floor(m/60),r=m%60;return h?`${h}h ${String(r).padStart(2,'0')}min`:`${r} min`}
function fmtTimer(ms){ms=Math.max(0,num(ms));const s=Math.floor(ms/1000),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),r=s%60;return [h,m,r].map(x=>String(x).padStart(2,'0')).join(':')}
function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}
function state(){return mirror?.state||{}}
function currentStep(j){return j?.payload?.current||null}
function lastStep(j){const a=j?.payload?.steps;return Array.isArray(a)&&a.length?a[a.length-1]:null}
function journeyStart(j){const c=currentStep(j);return num(c?.start||j?.payload?.start||(j?.saida_em?new Date(j.saida_em).getTime():0))}
function journeyElapsed(j){const c=currentStep(j);if(c?.start)return Date.now()-num(c.start);const l=lastStep(j);if(l?.start&&l?.actualEnd)return num(l.actualEnd)-num(l.start);return 0}
function journeyProgress(j){if(j.grupo==='finalized')return 100;const c=currentStep(j);if(!c)return j.grupo==='completed'?100:0;const st=num(c.start),en=num(c.end);if(!st||!en||en<=st)return 0;return Math.max(3,Math.min(100,(Date.now()-st)/(en-st)*100))}
function displayRouteParts(j){const c=currentStep(j),l=lastStep(j);const o=String(c?.origin||l?.origin||j.origem||j.frente||'').trim();const d=String(c?.destination||l?.destination||j.destino||'').trim();return [o||'--',d||'--']}
function truckMultiplier(frota){const t=state()?.logistics?.truckTypes?.[String(frota)];return t==='duque'?2:t==='tremiado'?3:1}
function stepTons(step,row){const front=String(step?.origin||row?.frente||'');const snap=num(step?.tonsPerTripSnapshot,NaN),mult=num(step?.truckMultiplierSnapshot,NaN);if(Number.isFinite(snap)&&Number.isFinite(mult))return snap*mult;const base=num(state()?.logistics?.fronts?.[front]?.tonsPerTrip,0);return base*truckMultiplier(row?.frota||row?.payload?.truck)}
function validDeliveryDestination(v){return ['Usina','Usina Vicentina','Vicentina','Adecoagro','Gadotti','Central'].includes(String(v||''))}

function deliveredMap(){const start=todayStart(),out={};for(const row of journeys){for(const st of(row?.payload?.steps||[])){const end=num(st.actualEnd),origin=String(st.origin||'');if(end>=start&&origin&&validDeliveryDestination(st.destination))out[origin]=(out[origin]||0)+stepTons(st,row)}}return out}
function completedStepsToday(){const start=todayStart(),out=[];for(const row of journeys)for(const st of(row?.payload?.steps||[])){const end=num(st.actualEnd);if(end>=start)out.push({row,step:st,end})}return out}
function deliveryTimes(){return completedStepsToday().filter(x=>validDeliveryDestination(x.step.destination)).map(x=>x.end).filter(Boolean)}
function averageSamples(){const trip=[],load=[];for(const r of journeys){for(const st of(r?.payload?.steps||[])){const d=num(st.actualEnd)-num(st.start);if(d>=5*60000&&d<=18*3600000)trip.push(d)}for(const e of(r?.payload?.loadingEvents||[])){const d=num(e.duration);if(d>=2*60000&&d<=12*3600000)load.push(d)}}return {trip,load}}
function frontAvg(name){const a=[];for(const r of journeys){if(String(r.frente||'')!==String(name))continue;for(const st of(r?.payload?.steps||[])){const d=num(st.actualEnd)-num(st.start);if(d>=5*60000&&d<=18*3600000)a.push(d)}}return avg(a)}
function groups(){const g={active:0,completed:0,transfer:0,finalized:0},running=new Set();for(const j of journeys){if(g[j.grupo]!==undefined)g[j.grupo]++;if(j.grupo!=='finalized')running.add(String(j.frota||j.payload?.truck||''))}return {g,running:[...running].filter(Boolean)}}
function overviewStats(){const fronts=state()?.logistics?.fronts||{},dm=deliveredMap();const meta=Object.values(fronts).filter(x=>x?.active!==false).reduce((s,x)=>s+num(x?.target),0);const real=Object.values(dm).reduce((a,b)=>a+b,0);const pct=meta?real/meta*100:0;const ts=deliveryTimes(),first=ts.length?Math.min(...ts):0,hours=first?Math.max(.5,(Date.now()-first)/3600000):0,proj=hours?real/hours*24:0,projPct=meta?proj/meta*100:0;return {fronts,dm,meta,real,pct,proj,projPct}}
function activeTrucksForFront(name){const s=new Set();for(const j of journeys){if(j.grupo==='finalized')continue;const [o,d]=displayRouteParts(j);if(String(j.frente||'')===name||o===name||d===name)s.add(String(j.frota||j.payload?.truck||''))}return [...s].filter(Boolean).length}

async function fetchAll(){const [jr,st]=await Promise.all([supabase.from('journeys').select('monitor_id,frota,frente,status,etapa,origem,destino,saida_em,chegada_em,previsao_chegada,grupo,payload,atualizado_em').order('atualizado_em',{ascending:false}),supabase.from('settings').select('valor,atualizado_em').eq('chave','coa_mirror_state').maybeSingle()]);if(jr.error)throw jr.error;if(st.error)throw st.error;journeys=jr.data||[];mirror=st.data?.valor||null;lastOk=Date.now()}

async function loadDesktopIcons(){try{const src=await fetch('./desktop.html?icons=20261003',{cache:'force-cache'}).then(r=>r.ok?r.text():Promise.reject());const m=src.match(/const ICONS=(\{[\s\S]*?\});\s*const KEY=/);if(m){iconMap=JSON.parse(m[1]);renderEquipment()}}catch(e){console.warn('[CEV mobile icons]',e)}}
function equipmentIconKey(e){const explicit=String(e?.icon||'');if(explicit&&iconMap[explicit])return explicit;const type=String(e?.type||'').toUpperCase(),model=String(e?.model||'').toUpperCase();if(type.includes('COLH'))return model.includes('CASE')?'colhedora_case':'colhedora_jd';if(type.includes('TRAT'))return model.includes('CASE')||model.includes('PUMA')?'trator_case':'trator_jd';return ''}
function equipmentStatus(s){return s==='operation'?['Operando','operation']:s==='maintenance'?['Manutenção','maintenance']:s==='scheduled'?['Programada','scheduled']:s==='lubrication'?['Lubrificação','lubrication']:['Parado','scheduled']}

function renderConnection(){const online=!!mirror&&Date.now()-lastOk<10000;$('onlineDot').classList.toggle('warn',!online);$('onlineText').textContent=online?'Acompanhamento operacional':'Aguardando atualização';$('updatedText').textContent=online?'● atualizado agora':'● sem atualização'}
function renderHome(){const {g,running}=groups(),o=overviewStats();$('kpiTrajeto').textContent=g.active;$('kpiCarregando').textContent=g.completed;$('kpiTransfer').textContent=g.transfer;$('kpiRodando').textContent=running.length;$('realizadoDia').textContent=formatTons(o.real);$('metaSub').textContent=`de ${formatTons(o.meta)} planejadas`;$('metaPct').textContent=`${pt1.format(o.pct)}%`;$('metaProgress').style.width=`${Math.min(100,o.pct)}%`;$('projectionMini').textContent=`Projeção 24h: ${formatTons(o.proj)}`;renderRecommendation(o);renderHomeFronts(o);renderConnection()}
function renderRecommendation(o){const rows=Object.entries(o.fronts).filter(([,c])=>c?.active!==false&&num(c?.target)>0).map(([name,c])=>({name,target:num(c.target),real:num(o.dm[name]),deficit:Math.max(0,num(c.target)-num(o.dm[name])),trucks:activeTrucksForFront(name),avg:frontAvg(name)})).sort((a,b)=>b.deficit-a.deficit);const r=rows[0];if(!r){$('recFront').textContent='--';$('recTitle').textContent='Sem recomendação no momento';$('recReason').textContent='Aguardando metas e entregas das frentes.';$('recDeficit').textContent='--';$('recCycle').textContent='--';$('recTrucks').textContent='--';return}$('recFront').textContent=r.name.toUpperCase();$('recTitle').textContent=`Próximo direcionamento sugerido → ${r.name}`;$('recReason').textContent='Frente com maior déficit momentâneo entre as metas ativas. Informação para acompanhamento; o despacho continua sendo feito pelo COA.';$('recDeficit').textContent=formatTons(r.deficit);$('recCycle').textContent=r.avg?fmtDuration(r.avg):'--';$('recTrucks').textContent=`${r.trucks} ativos`}
function renderHomeFronts(o){const names=Object.keys(o.fronts).filter(n=>o.fronts[n]?.active!==false);$('homeFronts').innerHTML=names.length?names.slice(0,6).map(name=>{const c=o.fronts[name]||{},meta=num(c.target),real=num(o.dm[name]),pct=meta?real/meta*100:0,trucks=activeTrucksForFront(name),cy=frontAvg(name);return `<div class="card frontMini"><div><div class="frontTop"><i class="frontDot"></i><span class="frontName">${esc(name)}</span></div><div class="frontMeta">${trucks} caminhões${cy?` • tempo ${esc(fmtDuration(cy))}`:''}</div></div><div class="frontRight"><strong>${pt1.format(pct)}%</strong><small>${formatTons(real)} / ${formatTons(meta)}</small></div><div class="miniBar"><i style="width:${Math.min(100,pct)}%"></i></div></div>`}).join(''):'<div class="empty">Sem frentes configuradas.</div>'}

function statusInfo(group){return group==='active'?['EM VIAGEM','active']:group==='completed'?['CARREGANDO','active']:group==='transfer'?['DESLOCAMENTO','move']:['CONCLUÍDA','done']}
function filteredTrips(){const start=todayStart();if(tripFilter==='ongoing')return journeys.filter(j=>['active','completed'].includes(j.grupo));if(tripFilter==='transfer')return journeys.filter(j=>j.grupo==='transfer');return journeys.filter(j=>j.grupo==='finalized'&&new Date(j.atualizado_em||0).getTime()>=start)}
function renderTrips(){const rows=filteredTrips();$('tripCount').textContent=String(rows.length);$('tripList').innerHTML=rows.length?rows.slice(0,100).map(j=>{const [label,cls]=statusInfo(j.grupo),[origin,dest]=displayRouteParts(j),prog=journeyProgress(j),c=currentStep(j),eta=c?.end||j.previsao_chegada,start=journeyStart(j);return `<div class="card trip ${cls}" data-trip-id="${esc(j.monitor_id||'')}"><div class="tripHead"><div class="tripId"><div class="tripIcon">🚛</div><div><strong>${esc(j.frota||j.payload?.truck||'-')}</strong><small>${esc(j.frente||'Monitor CEV')}</small></div></div><span class="status">${label}</span></div><div class="route"><span>${esc(origin)}</span><i></i><span>${esc(dest)}</span></div><div class="tripTimes"><span>Saída ${fmtClock(start)}</span><span>${j.grupo==='finalized'?'Fim':'Prev.'} ${j.grupo==='finalized'?fmtClock(j.chegada_em||lastStep(j)?.actualEnd):fmtClock(eta)}</span></div><div class="miniBar"><i style="width:${prog}%"></i></div><div class="tripFoot"><span class="timer" data-start="${start}" data-group="${esc(j.grupo)}">${fmtTimer(journeyElapsed(j))}</span><span class="tap">Ver detalhes ›</span></div></div>`}).join(''):'<div class="empty">Nenhuma viagem neste filtro.</div>'}

function renderFronts(){const o=overviewStats(),cfg=o.fronts,eq=state()?.effective_equipment?.data||[],names=Object.keys(cfg);$('frontCount').textContent=String(names.length);$('frontList').innerHTML=names.length?names.map(name=>{const c=cfg[name]||{},meta=num(c.target),real=num(o.dm[name]),pct=meta?real/meta*100:0,trucks=activeTrucksForFront(name),equip=eq.filter(e=>e.front===name),run=equip.filter(e=>e.status==='operation').length,cy=frontAvg(name);return `<div class="card frontDetail"><div class="fdHead"><div><h3>🌾 ${esc(name)}</h3><div class="frontMeta">${c.active===false?'Inativa':'Em operação'}${cy?` • tempo médio ${esc(fmtDuration(cy))}`:''}</div></div><span>${pt1.format(pct)}% DA META</span></div><div class="fdGrid"><div class="fdItem"><small>Meta</small><b>${formatTons(meta)}</b></div><div class="fdItem"><small>Entregue</small><b>${formatTons(real)}</b></div><div class="fdItem"><small>Falta</small><b>${formatTons(Math.max(0,meta-real))}</b></div><div class="fdItem"><small>Caminhões</small><b>${trucks}</b></div><div class="fdItem"><small>Equipamentos</small><b>${run}/${equip.length}</b></div><div class="fdItem"><small>t/viagem</small><b>${pt1.format(num(c.tonsPerTrip))}</b></div><div class="fdItem"><small>Tempo médio</small><b>${cy?fmtDuration(cy):'--'}</b></div><div class="fdItem"><small>Status</small><b>${c.active===false?'Inativa':'Ativa'}</b></div></div><div class="fdProgress"><div class="fdProgressLine"><span>Progresso</span><b>${pt1.format(pct)}%</b></div><div class="miniBar"><i style="width:${Math.min(100,pct)}%"></i></div></div></div>`}).join(''):'<div class="empty">Sem frentes configuradas.</div>'}

function renderEquipment(){const all=clone(state()?.effective_equipment?.data||[]),run=all.filter(e=>e.status==='operation').length,maint=all.filter(e=>e.status==='maintenance').length;$('eqTotal').textContent=all.length;$('eqRun').textContent=run;$('eqMaint').textContent=maint;$('eqStop').textContent=Math.max(0,all.length-run-maint);let a=all;if(equipFilter==='maintenance')a=a.filter(e=>e.status==='maintenance');else if(equipFilter!=='all')a=a.filter(e=>String(e.type||'').toUpperCase()===equipFilter);a.sort((x,y)=>String(x.front||'').localeCompare(String(y.front||''),'pt-BR')||String(x.fleet||'').localeCompare(String(y.fleet||'')));$('equipCount').textContent=String(a.length);const grouped={};for(const e of a)(grouped[e.front||'Sem frente']??=[]).push(e);$('equipList').innerHTML=Object.keys(grouped).length?Object.entries(grouped).map(([front,items])=>{const r=items.filter(e=>e.status==='operation').length;return `<div class="card eqFront"><div class="eqTitle"><h3>${esc(front)}</h3><small>${r} / ${items.length} operando</small></div><div class="eqGrid">${items.map(e=>{const [st,sc]=equipmentStatus(e.status),key=equipmentIconKey(e),src=iconMap[key];return `<div class="machine"><div class="machineVisual">${src?`<img src="${src}" alt="">`:'<span>🚜</span>'}</div><div><strong>${esc(e.fleet||'-')}</strong><small>${esc(e.model||e.type||'Equipamento')}</small><span class="ms ${sc}"><i></i>${esc(st)}</span></div></div>`}).join('')}</div></div>`}).join(''):'<div class="empty">Nenhum equipamento neste filtro.</div>'}

function renderMore(){const g=groups(),o=overviewStats(),sm=averageSamples(),maint=state()?.operational_extras?.maintenance||[],eq=state()?.effective_equipment?.data||[],run=eq.filter(e=>e.status==='operation').length;$('moreCycle').textContent=sm.trip.length?fmtDuration(avg(sm.trip)):'--';$('moreShipments').textContent=String(completedStepsToday().length);$('moreRunning').textContent=`${g.running.length} ativos`;$('moreMaintenance').textContent=`${maint.length} frotas`;$('proj24').textContent=formatTons(o.proj);$('moreEffectiveness').textContent=eq.length?`${pt1.format(run/eq.length*100)}%`:'0%'}
function renderAll(){renderHome();renderTrips();renderFronts();renderEquipment();renderMore()}

function sheet(title,sub,html){$('sheetTitle').textContent=title;$('sheetSub').textContent=sub;$('sheetBody').innerHTML=html;$('detailSheet').classList.add('open');$('detailSheet').setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closeSheet(){$('detailSheet').classList.remove('open');$('detailSheet').setAttribute('aria-hidden','true');document.body.style.overflow=''}
function openTripDetail(id){const j=journeys.find(x=>String(x.monitor_id)===String(id));if(!j)return;const [o,d]=displayRouteParts(j),[label]=statusInfo(j.grupo),start=journeyStart(j),c=currentStep(j),eta=c?.end||j.previsao_chegada;sheet(`🚛 Frota ${j.frota||j.payload?.truck||'-'}`,label,`<div class="sheetGrid"><div class="sheetItem"><small>Origem</small><b>${esc(o)}</b></div><div class="sheetItem"><small>Destino</small><b>${esc(d)}</b></div><div class="sheetItem"><small>Saída</small><b>${fmtClock(start)}</b></div><div class="sheetItem"><small>Previsão / fim</small><b>${fmtClock(j.grupo==='finalized'?(j.chegada_em||lastStep(j)?.actualEnd):eta)}</b></div><div class="sheetItem"><small>Tempo</small><b>${fmtTimer(journeyElapsed(j))}</b></div><div class="sheetItem"><small>Frente</small><b>${esc(j.frente||'-')}</b></div></div>`)}
function openMore(type){const o=overviewStats(),sm=averageSamples(),maint=state()?.operational_extras?.maintenance||[],g=groups();if(type==='tempo'){sheet('⏱️ Análise de tempo','Resumo das viagens concluídas',`<div class="sheetGrid"><div class="sheetItem"><small>Tempo médio</small><b>${sm.trip.length?fmtDuration(avg(sm.trip)):'--'}</b></div><div class="sheetItem"><small>Carregamento médio</small><b>${sm.load.length?fmtDuration(avg(sm.load)):'--'}</b></div><div class="sheetItem"><small>Amostras</small><b>${sm.trip.length}</b></div><div class="sheetItem"><small>Atualização</small><b>2 s</b></div></div>`)}else if(type==='envios'){const rows=completedStepsToday().slice(0,30);sheet('📦 Envios do dia',`${rows.length} movimentações recentes`,rows.length?`<div class="sheetList">${rows.map(x=>`<div class="sheetRow"><b>${esc(x.row.frota||'-')}</b> • ${esc(x.step.origin||'-')} → ${esc(x.step.destination||'-')} • ${fmtClock(x.end)}</div>`).join('')}</div>`:'<div class="empty">Nenhum envio registrado hoje.</div>')}else if(type==='operacao'){sheet('🏭 Operação atual','Situação dos caminhões',`<div class="sheetGrid"><div class="sheetItem"><small>Em trajeto</small><b>${g.g.active}</b></div><div class="sheetItem"><small>Carregando</small><b>${g.g.completed}</b></div><div class="sheetItem"><small>Deslocamento</small><b>${g.g.transfer}</b></div><div class="sheetItem"><small>Ativos</small><b>${g.running.length}</b></div></div>`)}else if(type==='manutencao'){sheet('🔧 Manutenção',`${maint.length} frotas registradas`,maint.length?`<div class="sheetList">${maint.map(x=>`<div class="sheetRow"><b>Frota ${esc(x.fleet||x.frota||'-')}</b>${x.start?` • desde ${fmtClock(x.start)}`:''}</div>`).join('')}</div>`:'<div class="empty">Nenhuma frota em manutenção.</div>')}else if(type==='projecao'){sheet('📈 Projeção 24h','Estimativa pelo ritmo de entregas',`<div class="sheetGrid"><div class="sheetItem"><small>Projeção</small><b>${formatTons(o.proj)}</b></div><div class="sheetItem"><small>Meta</small><b>${formatTons(o.meta)}</b></div><div class="sheetItem"><small>Projeção x meta</small><b>${pt1.format(o.projPct)}%</b></div><div class="sheetItem"><small>Entregue hoje</small><b>${formatTons(o.real)}</b></div></div>`)} }

function tickTimers(){document.querySelectorAll('.timer[data-start]').forEach(el=>{const st=num(el.dataset.start);if(st&&el.dataset.group!=='finalized')el.textContent=fmtTimer(Date.now()-st)});renderConnection()}
async function refresh(){if(busy||document.hidden||!currentUser)return;busy=true;try{await fetchAll();renderAll()}catch(e){console.error('[CEV mobile refresh]',e);$('onlineDot')?.classList.add('warn');if($('onlineText'))$('onlineText').textContent='Falha na atualização'}finally{busy=false}}
async function loadAuthorized(user){const {data:p,error}=await supabase.from('profiles').select('nome,role,ativo,email').eq('id',user.id).single();if(error)throw error;if(!p?.ativo)throw new Error('Usuário desativado.');currentUser=user;profile=p;$('auth').classList.add('hidden');$('app').hidden=false;await Promise.allSettled([fetchAll(),loadDesktopIcons()]);renderAll()}

$('login').addEventListener('click',async()=>{const email=$('email').value.trim(),password=$('password').value;if(!email||!password){$('authStatus').textContent='Informe e-mail e senha.';$('authStatus').className='authStatus err';return}$('login').disabled=true;$('authStatus').textContent='Entrando...';try{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;await loadAuthorized(data.user)}catch(e){$('authStatus').textContent='❌ '+(e?.message||String(e));$('authStatus').className='authStatus err'}finally{$('login').disabled=false}});
$('password').addEventListener('keydown',e=>{if(e.key==='Enter')$('login').click()});
$('logout').addEventListener('click',async()=>{await supabase.auth.signOut();location.reload()});

document.querySelectorAll('.nav').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===btn.dataset.view));window.scrollTo({top:0,behavior:'smooth'})}));
$('tripFilters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;tripFilter=b.dataset.filter;[...$('tripFilters').children].forEach(x=>x.classList.toggle('active',x===b));renderTrips()});
$('equipFilters').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;equipFilter=b.dataset.filter;[...$('equipFilters').children].forEach(x=>x.classList.toggle('active',x===b));renderEquipment()});
$('tripList').addEventListener('click',e=>{const c=e.target.closest('[data-trip-id]');if(c)openTripDetail(c.dataset.tripId)});
document.querySelectorAll('[data-more]').forEach(b=>b.addEventListener('click',()=>openMore(b.dataset.more)));
document.querySelectorAll('[data-view-jump]').forEach(b=>b.addEventListener('click',()=>document.querySelector(`.nav[data-view="${b.dataset.viewJump}"]`)?.click()));
$('sheetClose').addEventListener('click',closeSheet);$('detailSheet').addEventListener('click',e=>{if(e.target===$('detailSheet'))closeSheet()});

setInterval(refresh,REFRESH_MS);setInterval(tickTimers,1000);
(async()=>{const {data:{session}}=await supabase.auth.getSession();if(session?.user){try{await loadAuthorized(session.user)}catch(e){$('authStatus').textContent='❌ '+(e?.message||String(e));$('authStatus').className='authStatus err'}}})();
